package com.airgroup.services.impl.airchina;

import com.ning.http.client.FluentStringsMap;
import com.airgroup.model.RequestType;
import com.airgroup.services.FlightResponse;

public class AirChinaRequest extends FlightResponse {


	public String getDateTimeFormatterPattern() {
		return "yyyyMMdd";
	}

	@Override
	public RequestType getType() {
		return RequestType.POST;
	}

	@Override
	public String getURL() {
		return "http://book.eu2.amadeus.com/plnext/airchina/Override.action";
	}

	@Override
	public String getHeaderValue() {
		return null;
	}

	@Override
	public FluentStringsMap getParams() {
		FluentStringsMap params = new FluentStringsMap();

		// params.add("TRAVELLER_TYPE_1", "ADT");
		// params.add("TRAVELLER_TYPE_2", "");
		// params.add("TRAVELLER_TYPE_3", "");
		// params.add("TRAVELLER_TYPE_4", "");

		int j = 0;
		for (int i = 1; i <= search.getAdultsCount(); i++) {
			params.add("TRAVELLER_TYPE_" + i, "ADT");
			j = i;
		}
		for (int i = 1; i <= search.getChildrenCount(); i++) {
			params.add("TRAVELLER_TYPE_" + (i + j), "CHD");
		}

		params.add("TRIP_TYPE", search.isRoundtrip() ? "R" : "O");

		params.add("CABIN", "E");
		params.add("B_DATE_1", getDateTimeFormatter().print(search.getOutboundDate()) + "0000");

		if (search.isRoundtrip()) {
			params.add("B_DATE_2", getDateTimeFormatter().print(search.getInboundDate()) + "0000");
			params.add("B_ANY_TIME_2", "TRUE");
		}

		params.add("B_ANY_TIME_1", "TRUE");
		params.add("B_LOCATION_1", "");
		params.add("E_LOCATION_1", "");
		params.add("EMBEDDED_TRANSACTION", "AirAvailability");
		params.add("SITE", "BBYQBBYQ");
		params.add("LANGUAGE", "GB");
		params.add("TRIPFLOW", "YES");
		params.add("EXTERNAL_ID", "VNEN");
		params.add("SO_SITE_OFFICE_ID", "SGNCA18AA");
		params.add("DIRECT_LOGIN", "NO");
		params.add("HAS_INFANT_1", "FALSE");
		params.add("HAS_INFANT_2", "FALSE");
		params.add("HAS_INFANT_3", "FALSE");
		params.add("HAS_INFANT_4", "FALSE");
		params.add("SEVEN_DAY_SEARCH", "TRUE");
		params.add("SO_QUEUE_NUMBER", "10");
		params.add("ENCT", "1");
		params.add("ENC", (String) search.getParamValue("ENC"));
		params.add("SO_SITE_QUEUE_OFFICE_ID", "SGNCA12TK");
		params.add("SO_QUEUE_CATEGORY", "0");
		params
			.add(
				"SO_GL",
				"<?xml version='1.0' encoding='iso-8859-1'?><SO_GL><GLOBAL_LIST mode='complete'><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>0</CODE><LIST_VALUE>0</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>1</CODE><LIST_VALUE>1</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>TRUE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>2</CODE><LIST_VALUE>0</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>3</CODE><LIST_VALUE>1</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>TRUE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>4</CODE><LIST_VALUE>0</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>5</CODE><LIST_VALUE>1</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>TRUE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT><NAME>SITE_SITE_FARE_COMMANDS_AND_OPTIONS</NAME><LIST_ELEMENT><CODE>6</CODE><LIST_VALUE>1</LIST_VALUE><LIST_VALUE>2</LIST_VALUE><LIST_VALUE>4</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>USD</LIST_VALUE><LIST_VALUE>TRUE</LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE><LIST_VALUE></LIST_VALUE><LIST_VALUE>FALSE</LIST_VALUE></LIST_ELEMENT></GLOBAL_LIST></SO_GL>");
		params.add("SO_SITE_ARRANGE_BY_INCLUDE", "1");
		params.add("SO_SITE_ET_CODE_SHARE", "00");
		params.add("SO_SITE_MIN_AVAIL_DATE_SPAN", "H12");
		params.add("SO_SITE_MINIMAL_TIME", "H12");
		params.add("SO_SITE_PNR_ADD_EMAIL1", "catest@airchina.com");
		params.add("SO_SITE_TK_TIME_PERIOD", "H12");
		params.add("SO_SITE_UP_SELL_ALLOWED", "TRUE");
		params.add("SO_SITE_IS_INSURANCE_ENABLED", "FALSE");

		return params;
	}
}
